version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8585:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
#      - ./style.css:/usr/share/nginx/html/style.css
#      - ./script.js:/usr/share/nginx/html/script.js
    restart: always